import { Box, Flex } from "@chakra-ui/react";
import React from "react";

const NavDropDown = () => {
    return <Flex></Flex>;
};

export default NavDropDown;
const catrgories = [
    {
        id: 1,
        text: "Hair Products",
        catrgory: "Hair care products",
        children: [
            "Shampoo",
            "Hair Masks",
            "Leave-in Conditioner",
            "Conditioner",
            "Hair Serums",
            "Scalp Treatment",
            "Baby’s Hair",
            "Hair Dyes",
            "Hair Gels & Glues",
            "Hair Oils",
            "Texturizer",
        ],
    },
    {
        id: 2,
        text: "Skin Care",
        catrgory: "Hair Styling Products",
        children: [
            "Detanglers",
            "Styling Gels",
            "Fragrances",
            "Sprays",
            "Root Lifting Powders",
            "Salt Water Sprays",
            "Styling Pomades",
            "Styling Waxes",
            "Styling Clays",
            "Styling Creams & Lotions",
            "Hair Tonic",
            "Styling Foams",
        ],
    },
    {
        id: 3,
        text: "Hair Styling",
        catrgory: "Skin Care Products",
        children: [
            "Detanglers",
            "Styling Gels",
            "Fragrances",
            "Sprays",
            "Root Lifting Powders",
            "Salt Water Sprays",
            "Styling Oils",
            "Styling Serums",
            "Styling Pomades",
            "Styling Waxes",
            "Styling Clays",
            "Styling Creams & Lotions",
            "Styling Foams",
            "Hair Tonic",
            "Styling Mouses",
            "Styling Putties",
            "Thermal Protection Sprays",
        ],
    },
    {
        id: 4,
        text: "Skin Care",
        catrgory: "Skin Care Products",
        children: [
            "Detanglers",
            "Styling Gels",
            "Fragrances",
            "Sprays",
            "Root Lifting Powders",
            "Salt Water Sprays",
            "Styling Oils",
            "Styling Serums",
            "Styling Pomades",
            "Styling Waxes",
            "Styling Clays",
            "Styling Creams & Lotions",
            "Styling Foams",
            "Hair Tonic",
            "Styling Mouses",
            "Styling Putties",
            "Thermal Protection Sprays",
        ],
    },
    {
        id: 4,
        text: "Hair Care",
        catrgory: "Hair Care",
        children: [
            "Dandruff Treatment",

            "Dryness Treatment",
            "Natural Hair Care",
            "Scalp Care",
            "Damaged Hair Care",
            "Color Care",
            "Tea Tree",
            "Sheabutter",
            "Charcoal",
            "Ayurvedic",
            "Honey",
        ],
    },
];
