export const whatsNew = [
    {
        id: 1,
        imageUrl: "/images/np_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 1,
        price: "3,500",
    },
    {
        id: 2,
        imageUrl: "/images/np_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 2,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_3.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 3,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/shampoo_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 4,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/scp_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 5,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 1,
        price: "3,500",
    },
    {
        id: 2,
        imageUrl: "/images/np_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 2,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_3.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 3,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/shampoo_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 4,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/scp_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 5,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 1,
        price: "3,500",
    },
    {
        id: 2,
        imageUrl: "/images/np_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 2,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_3.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 3,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/shampoo_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 4,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/scp_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 5,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 1,
        price: "3,500",
    },
    {
        id: 2,
        imageUrl: "/images/np_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 2,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_3.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 3,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/shampoo_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 4,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/scp_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 5,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 1,
        price: "3,500",
    },
    {
        id: 2,
        imageUrl: "/images/np_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 2,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_3.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 3,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/shampoo_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 4,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/scp_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 5,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 1,
        price: "3,500",
    },
    {
        id: 2,
        imageUrl: "/images/np_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 2,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_3.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 3,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/shampoo_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 4,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/scp_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 5,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 1,
        price: "3,500",
    },
    {
        id: 2,
        imageUrl: "/images/np_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 2,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_3.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 3,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/shampoo_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 4,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/scp_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 5,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 1,
        price: "3,500",
    },
    {
        id: 2,
        imageUrl: "/images/np_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 2,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/np_3.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 3,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/shampoo_2.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 4,
        price: "3,500",
    },
    {
        id: 1,
        imageUrl: "/images/scp_1.svg",
        text: "Pomegranate & Honey Moisturizing and Detangling Shampoo 355ml",
        rating: 5,
        price: "3,500",
    },
];

export const dummyProduct = [
    {
        id: 1,
        name: "Face mask",
        actual_price: 8000,
        sales_price: 5000,
        first_description: "This is the first description and all",
        second_description: "This is the second description",
        views: 1,
        product_img: "/media/images/IMG-6768_bG1qDFE.jpg",
        sub_category: 2,
        comment: [
            {
                id: 1,
                comment: "This is a comment to delete",
                rate: 3,
                commenter: 1,
                product: 1,
            },
            {
                id: 2,
                comment: "This is a comment to delete",
                rate: 3,
                commenter: 2,
                product: 1,
            },
        ],
    },
    {
        id: 2,
        name: "Face masking",
        actual_price: 4700,
        sales_price: 5000,
        first_description: "This is the first description",
        second_description: "This is the second description",
        views: 0,
        product_img: "/media/images/IMG-6768_uJ9fdOW.jpg",
        sub_category: 1,
        comment: [
            {
                id: 3,
                comment: "This is a comment to",
                rate: 4,
                commenter: 2,
                product: 2,
            },
        ],
    },
    {
        id: 3,
        name: "Face lotion",
        actual_price: 8000,
        sales_price: 5000,
        first_description: "This is the first description and all",
        second_description: "This is the second description",
        views: 0,
        product_img: "/media/images/IMG-6768_0YAQMl0.jpg",
        sub_category: 2,
        comment: [],
    },
    {
        id: 4,
        name: "Face cleanser",
        actual_price: 4700,
        sales_price: 5000,
        first_description: "This is the first description",
        second_description: "This is the second description",
        views: 2,
        product_img: "/media/images/IMG-6768_H9s1yHO.jpg",
        sub_category: 1,
        comment: [],
    },
    {
        id: 5,
        name: "Face shine",
        actual_price: 8000,
        sales_price: 5000,
        first_description: "This is the first description and all",
        second_description: "This is the second description",
        views: 0,
        product_img: "/media/images/IMG-6768_SeA7tn4.jpg",
        sub_category: 3,
        comment: [],
    },
    {
        id: 6,
        name: "Face scrub",
        actual_price: 4700,
        sales_price: 5000,
        first_description: "This is the first description",
        second_description: "This is the second description",
        views: 0,
        product_img: "/media/images/IMG-6768_fjd9nry.jpg",
        sub_category: 1,
        comment: [],
    },
    {
        id: 7,
        name: "Face soul",
        actual_price: 4700,
        sales_price: 5000,
        first_description: "This is the first description",
        second_description: "This is the second description",
        views: 0,
        product_img: "/media/images/IMG-6768_1Wa20Cs.jpg",
        sub_category: 1,
        comment: [],
    },
    {
        id: 8,
        name: "Face sun",
        actual_price: 4700,
        sales_price: 5000,
        first_description: "This is the first description",
        second_description: "This is the second description",
        views: 0,
        product_img: "/media/images/IMG-6768_OdCdkSJ.jpg",
        sub_category: 2,
        comment: [],
    },
    {
        id: 9,
        name: "Face spoon",
        actual_price: 4700,
        sales_price: 5000,
        first_description: "This is the first description",
        second_description: "This is the second description",
        views: 0,
        product_img: "/media/images/IMG-6768.jpg",
        sub_category: 2,
        comment: [],
    },
];
