export const categories = [
    {
        id: 1,
        text: "Hair Products",
        category: "Hair care products",
        children: [
            "Shampoo",
            "Hair Masks",
            "Leave-in Conditioner",
            "Conditioner",
            "Hair Serums",
            "Scalp Treatment",
            "Baby’s Hair",
            "Hair Dyes",
            "Hair Gels & Glues",
            "Hair Oils",
            "Texturizer",
        ],
    },
    {
        id: 2,
        text: "Hair Styling",
        category: "Hair Styling Products",
        children: [
            "Detanglers",
            "Styling Gels",
            "Fragrances",
            "Sprays",
            "Root Lifting Powders",
            "Salt Water Sprays",
            "Styling Pomades",
            "Styling Waxes",
            "Styling Clays",
            "Styling Creams & Lotions",
            "Hair Tonic",
            "Styling Foams",
        ],
    },
    {
        id: 3,
        text: "Skin Care",
        category: "Skin Care Products",
        children: [
            "Detanglers",
            "Styling Gels",
            "Fragrances",
            "Sprays",
            "Root Lifting Powders",
            "Salt Water Sprays",
            "Styling Oils",
            "Styling Serums",
            "Styling Pomades",
            "Styling Waxes",
            "Styling Clays",
            "Styling Creams & Lotions",
            "Styling Foams",
            "Hair Tonic",
            "Styling Mouses",
            "Styling Putties",
            "Thermal Protection Sprays",
        ],
    },

    {
        id: 4,
        text: "Hair Care",
        category: "Hair Care",
        children: [
            "Dandruff Treatment",
            "Dryness Treatment",
            "Natural Hair Care",
            "Scalp Care",
            "Damaged Hair Care",
            "Color Care",
            "Tea Tree",
            "Sheabutter",
            "Charcoal",
            "Ayurvedic",
            "Honey",
        ],
    },
    {
        id: 5,
        text: "Equipments & Tools",
        category: "Hair Equipments",
        children: [
            "Hair Dryer",
            "Curling Iron",
            "Straightening iron",
            "Diffuser",
            "Hard Hat Dryer",
            "Roller Hairsetter",
            "Round Hair brush",
            "Detangling Comb",
        ],
    },
    {
        id: 6,
        text: "Accessories",
        category: "Hair Accessories",
        children: [
            "Hair Accessories",
            "Hair Claws",
            "Hair Ties",
            "Hair Clips",
            "Head Bands",
            "Scrunches",
            "Hair Bands",
            "Haarklemmen",
            "Haardonut",
            "Fashion Ring",
        ],
    },
    {
        id: 7,
        text: "Cosmetics",
        category: "Beauty & Personal Care",
        children: [
            "Lip Gloss",
            "Concealers & Neutralizing Makeup",
            "Face Blushes",
            "Eyeshadow",
            "Maskara",
            "Foundation primers",
            "Face Highlighters & Luminizers",
        ],
    },
];
